# Generated by Django 4.2.17 on 2024-12-14 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_venda_pago_venda_pegue_monte'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_movimentada', models.IntegerField()),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=200)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
            ],
        ),
    ]
