# Generated by Django 4.2.17 on 2024-12-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_movimentoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
