# Generated by Django 4.2.17 on 2024-12-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_produto_quantidade_estoque_venda_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='tipo_movimento',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='data_movimento',
            field=models.DateTimeField(auto_now=True, verbose_name='data movimento'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='quantidade_movimentada',
            field=models.PositiveIntegerField(),
        ),
    ]
